### ISSUE TITLE
The `$where` filter condition is not accepted in the MongoDB Atlas free tier

### ISSUE THREAD

**Issue by amanfrinati** [mongoid/mongoid-locker#100]
When I run my application in a MongoDB Atlas with free tier, I get this error

```
Mongo::Error::OperationFailure: [8000:AtlasError]: $where not allowed in this atlas tier
```

In my case, the problem is the `find_and_lock` function in the `lib/mongoid/locker/wrapper.rb` file.

**Comment by dblock** [comment]
Looks like https://stackoverflow.com/questions/54200300/how-do-i-solve-mongoerror-where-is-not-allowed-in-this-atlas-tier. Feel free to contribute a different implementation that works on all tiers.

**Comment by amanfrinati** [comment]
Thank you! I'll suggest you a change via pull request..
