### ISSUE TITLE
add named locks for iterating

### ISSUE THREAD

**Issue by afeld** [mongoid/mongoid-locker#15]

**Comment by dks17** [comment]
I have prepared PR for it.
How do you want to use named lock for iterating?

We can add new methods or change them. For example:
```ruby
module ClassMethods
  # A scope to retrieve all locked documents in the collection.
  #
  # @return [Mongoid::Criteria]
  def locked
    where(locked_name_field.exists: => true, locked_name_field.ne => nil)
  end

  def locked_expired
    where locked_until_field.gt => Time.now.utc
  end
```

Using `:locked_name` field allows us be free from fields with time.
Can we rely on `:locked_name` field in these cases?
