### ISSUE TITLE
Allow customizing locked_at field (clash with Devise).

### ISSUE THREAD

**Issue by stulentsev** [mongoid/mongoid-locker#26]
mongoid-locker uses hardcoded field name `:locked_at`. This is also the name that is hardcoded into `Devise::Lockable` module.

In our app that led to a nasty bug where users would be spontaneously logged out. Very annoying.

I tried to make the field configurable but I hated the result (code becomes quite uglier). So I won't be posting a PR now, I'm afraid.

In our app I fixed it by forking and hardcode-renaming the field: https://github.com/stulentsev/mongoid-locker/tree/alternate_field

A clash with such popular gem as Devise should be a serious problem. I'm actually surprised it didn't surface earlier.

**Comment by dblock** [comment]
Resolved in https://github.com/mongoid/mongoid-locker/pull/55. Please try HEAD!

**Comment by stulentsev** [comment]
Awesome news! I felt kinda bad about not following up on this :)
