### ISSUE TITLE
throws exception when not locked

### ISSUE THREAD

**Issue by pschrammel** [mongoid/mongoid-locker#29]
in locker.rb

```
unless opts[:retry_sleep]
            locked_until = Mongoid::Locker::Wrapper.locked_until(self)
            retry_sleep = locked_until - Time.now
end
```

but locked_until can (and does) return nil if not locked. So locked_until - Time.now throws error.

Sorry, no patch as I'm not that familiar with mongo + locker

**Comment by sivagollapalli** [comment]
Looks like this issue has been fixed. https://github.com/mongoid/mongoid-locker/blob/master/lib/mongoid/locker.rb#L140

**Comment by dblock** [comment]
Closing.
