### ISSUE TITLE
<Mongoid::Locker::LockError: could not get lock>

### ISSUE THREAD

**Issue by ghost** [mongoid/mongoid-locker#39]
Hi,

  I am getting this issue when I am trying to add with_lock block on my initialized object so can anyone help me,how can I resolve this?

**Comment by dblock** [comment]
That happens [in a loop](https://github.com/afeld/mongoid-locker/blob/a11db7672c34e5cab7ea5d1a180f53e06a552155/lib/mongoid/locker.rb#L146) so depends on your `lock` options. Post some more code?

**Comment by mnagdewani-systango** [comment]
Here is my loop code :
spotify_tracks.each.with_index(1) do |spotify_track, index|
      
      unless spotify_track.added_at.present?
        logger.info "NULL added_at track : name #{spotify_track.name} : spotify track id #{spotify_track.id}" if logger
        # next
      end
      # begin
        track_added_at = platform_type == 'Spotify' ? (spotify_track.added_at.to_datetime rescue Time.at(0).utc.to_datetime) : (spotify_track.added_at.present? ? Time.at(spotify_track.added_at).utc : Time.at(0).utc.to_datetime)
      # rescue
      #   logger.info "Not adding track, because track dont have VALID added_at : name #{spotify_track.name} : spotify track id #{spotify_track.id}" if logger
      #   next
      # end

      #we can remove it because now we are not passing market now to get is_playable and handling this at APP end.
      # is_playable = (spotify_track.is_playable.nil? ? true : spotify_track.is_playable)
      #track = self.with_spotify_id(spotify_track.id).first
      track = self.with_platform_id(spotify_track.id,platform_type).first

      if track.present?
        logger.info "Existing track in DB with spotify track id #{spotify_track.id}" if logger
        tracks << track
        track.set(added_at: track_added_at)
        # track.set(is_playable: is_playable)
        next 
      end

      # else
        if platform_type=='Spotify'
          isrc_code = spotify_track.external_ids.present? ? spotify_track.external_ids['isrc'] : nil
          url = spotify_track.external_urls['spotify'] rescue nil
        else
          isrc_code = spotify_track.isrc.present? ? spotify_track.isrc : nil
          url = spotify_track.url.present? ? spotify_track.url : nil
        end  

          track_hash = {
            duration_ms: spotify_track.duration_ms,
            added_at: track_added_at,
            created_at: DateTime.now,
            updated_at: DateTime.now,
            isrc_code: isrc_code
          }

          metadata = {
             preview_url: spotify_track.preview_url,
             popularity: spotify_track.popularity,
             available_markets: (spotify_track.available_markets rescue []),
             platform_id: spotify_track.id.to_s,
             url: url 
          }
          track_hash.merge!(spotify_name: spotify_track.name, spotify_track_metadata: metadata) if platform_type=='Spotify'
        
          track_hash.merge!(deezer_name: spotify_track.name, deezer_track_metadata: metadata) if platform_type=='Deezer'
          
       
          track = Track.new(track_hash)
          track.with_lock do

            if track.valid?

              Artist.get_and_create_artist(platform_type, spotify_track.artists, track)
              
              if platform_type=='Deezer' && spotify_track.album.class==Array
                spotify_track.album.each do |album|
                  Album.get_and_create_album(platform_type, album, track)
                end  
              else
                Album.get_and_create_album(platform_type, spotify_track.album, track)
              end
           
              if platform_type=='Spotify'
                track_hash.merge!({album_id: track.album_id, spotify_artists_ids: track.spotify_artists_ids})
              elsif platform_type == 'Deezer'
                track_hash.merge!({album_id: track.album_id, deezer_artists_ids: track.deezer_artists_ids})
              end  
              batch << track_hash 
              # created_spotify_tracks << spotify_track
              track.save!
            else
              if logger
                logger.info "Unable to create track due to error #{track.errors}"
              end
            end
          end      
      # end  
    end
    return tracks if batch.empty?

**Comment by dblock** [comment]
I don't see anything wrong here. I would enable Mongoid DEBUG logging and look at the queries being done, maybe it will show something obvious?

**Comment by dblock** [comment]
Also double-check which version of mongoid-locker and MongoDB you're using?

**Comment by mnagdewani-systango** [comment]
mongoid-locker (0.3.4) && Db version v3.2.1

**Comment by adriandiaz** [comment]
I'm having the same issue. Was this resolved? Ideally in my use case, if the document is currently locked I'd like to skip the block in `with_lock`. I've tried wrapping it in a begin/rescue but still get `<Mongoid::Locker::LockError: could not get lock>`. If I use the `locked?` method it doesn't work either cause there's the scenario where another process obtains the lock between the `locked?` check and the `with_lock` block.

**Comment by wuhuizuo** [comment]
I'm having the same issue. But i have solve it by wrap enhance. I will show my solution when i am waked up.

**Comment by wuhuizuo** [comment]
@adriandiaz sorry for late!
My solution example code:

```ruby
def get_lock(lock_type, token = gen_token, options = {})
        reload_get_lock = -> do
          begin
            success = with_lock do            
              # do your things
              true
            end
          rescue Mongoid::Locker::LockError
            false
          end
        end

        if option[:wait]    
          sleep_interval = option[:sleep_interval] || 1
          retry_times = option[:retry_times] || -1
          if retry_times > 0
            sleep(sleep_interval) until ((retry_times -= 1) >= 0 and reload_get_lock.call)
          else
            sleep(sleep_interval) until reload_get_lock.call
          end
          logger.info "#{self.class.name}(res_id:#{res_id}) -> [#{lock_type}] locked with #{token}."
        else
          reload_get_lock.call
        end       
end
```

**Comment by dks17** [comment]
It looks like `with_lock` is applied to not persisted document, but only new ruby object in memory. Necessary that ruby object be saved and became a `mongo` document before the document can be locked.
```ruby
      track = Track.new(track_hash)
      track.with_lock do
```

**Comment by dblock** [comment]
Closing via https://github.com/mongoid/mongoid-locker/pull/66
