### ISSUE TITLE
Uninitialized Constant Mongoid::Locker

### ISSUE THREAD

**Issue by anushamummina** [mongoid/mongoid-locker#49]
Hi There,

I am using 'mongoid-locker' gem  in my rails application. and applied locker to my user model like below:

```
class User
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Locker

```

It is working fine when I applied locks for a transaction. but when I am trying to load user in console I am getting `Uninitialized Constant Mongoid::Locker`.

Any help would be appreciated.

Thank you in Advance.

**Comment by dblock** [comment]
Sounds like it hasn't been required properly? Does adding `require 'mongoid/locker'` help?

**Comment by anushamummina** [comment]
@dblock Yes you are right Daniel. After adding gem I didn't restarted spring so console didn't identify the locker changes. My mistake.  Thank you so much for your help.
