### ISSUE TITLE
Simultaneous actions resulting unknown results sometimes.

### ISSUE THREAD

**Issue by anushamummina** [mongoid/mongoid-locker#50]
Hi There,

I am using `Mongoid-locker` gem to lock mongo document while writing data simultaneously.
I have a concept of sending amount from one user to other user in my app. I have field named "Balance" in my "User" Table
Example: `Two Users A, B`
My Scenario: `Sending amount  from A to B one after other working properly and it is fine. But when I am trying the same simultaneously sometimes amount are deducting/adding properly but sometimes it is failing.`

I have added `with_lock` for both receiver and sender with option `wait: true.`

I am thinking that we can do something like if we know that document is locked, then we can stop that transaction but I don't know how to check whether document gets locked or not.

Could you please assist me to solve this

**Comment by dblock** [comment]
I am going to close this. Please feel free to reopen @anushamummina if you can provide an example for how it's not working. What you describe seems correct and the lock should work as expected.
