### ISSUE TITLE
Add danger

### ISSUE THREAD

**Issue by dblock** [mongoid/mongoid-locker#53]
Just like for other mongoid org projects, add mongoid-danger.

**Comment by wuhuizuo** [comment]
I saw there has mongoid-danger in Gemfile, and there has Dangerfile.
you mean adding self project's danger rules? @dblock

**Comment by dblock** [comment]
It was already in https://github.com/mongoid/mongoid-locker/pull/48, I am just surprised that we didn't see a CHANGELOG warning on some formatting errors... maybe there's a problem with the key, I'll look.
