### ISSUE TITLE
add test for Airbrake notification

### ISSUE THREAD

**Issue by afeld** [mongoid/mongoid-locker#6]

**Comment by dks17** [comment]
Is this still relevant?
I have checked `Airbrake` [site](https://airbrake.io/pricing) and this is a paid service. `Mongoid-Locker` has only one [custom error](https://github.com/mongoid/mongoid-locker/blob/7703fe1a7176b4e8940823c76ed1cbb466a0ebf2/lib/mongoid/locker.rb#L11), and `Airbrake` notification can be [added](https://github.com/airbrake/airbrake-ruby) into an application.
