### ISSUE TITLE
Can we drop mongoid-compatibility gem dependency?

### ISSUE THREAD

**Issue by dks17** [mongoid/mongoid-locker#62]
It does not look difficult.

**Comment by dblock** [comment]
Why? That gem was introduced because in half the mongoid gems version checks were incorrect.

**Comment by dks17** [comment]
We have dropped support some old mongoid versions.
Mongoid gem has `VERSION` constant over versions we support. 
https://github.com/mongodb/mongoid/commits/master/lib/mongoid/version.rb

I think we can replace `mongoid-compatibility` gem dependency by simple version checking in the gem. Let me try to prepare PR for it.

**Comment by dblock** [comment]
I just don't understand what advantage this would have other than introducing more potential bugs. The mongoid-compatibility gem uses the version constant and has tested explicit methods for checking for mongoid versions including for ranges, such as `mongoid6_or_newer?`.

**Comment by dks17** [comment]
I think no need more functionality than it is actually needed.

Locker does not use `mongoid6_or_newer?` or `mongoid6_or_older?` methods. Do you think these methods will be used in the next releases?

That is almost all that `mongoid-compatibility` gem is for:
https://github.com/mongoid/mongoid-locker/blob/da15e7f16245e8af34e6d8235916ef76d317f8e2/lib/mongoid/locker/wrapper.rb#L1-L13

And it maybe replaced by
```ruby
if %w[4 5 6 7].include?(version = Mongoid::VERSION.split('.')[0])
  require "mongoid/locker/wrapper#{version}"
else
  raise 'incompatible Mongoid version'
end
```

I understand you beware introducing more potential bugs. Is this the only thing a blocker?

**Comment by dks17** [comment]
Added #65 PR.

Feel free to close the issue and the PR.

**Comment by dblock** [comment]
I've merged it, it's fine. 

I like external libraries that do things well, it's only a matter of time till someone does wrong version math, but we'll just have to watch for it.

**Comment by dblock** [comment]
Thanks for your work @dks17 !
