### ISSUE TITLE
Time.now is not monotonic

### ISSUE THREAD

**Issue by dblock** [mongoid/mongoid-locker#72]
See https://github.com/mongoid/mongoid-locker/pull/71#issuecomment-441259012

**Comment by dks17** [comment]
We could use local MongodDB server time. It allows using only one server clock instead of many different client clocks. We also could do something with uptime (looks `monotonic`) of MongoDB process.
In this case we have to do more job for locking, at least one additional query.

```ruby
pp User.collection.database.command({ serverStatus: 1 }).to_a
```

```console
[{"host"=>"comp11-ub",
  "version"=>"4.0.4",
  "process"=>"mongod",
  "pid"=>961,
  "uptime"=>19488.0,
  "uptimeMillis"=>23101668,
  "uptimeEstimate"=>23101,
  "localTime"=>2018-12-01 11:27:34 UTC,

```

**Comment by dblock** [comment]
It's a good idea @dks17.
