### ISSUE TITLE
Add example on how to write specs on operations that rely on Mongoid Lock to be safe

### ISSUE THREAD

**Issue by Startouf** [mongoid/mongoid-locker#84]
It would be convenient to have some examples of specs that validate race conditions.

For instance, how do I write a spec for the following service assuming 2 servers perform an operation that should be unsafe without Mongoid Lock, and safe with it, like withdrawing cash from an account ?

```ruby
class MyService
  def call(user:, cash_to_withdraw:)
    # user.with_lock do # how do I write a spec that fails without this wrapper ?
      if user.has_enough_cash_for(cash_to_withdraw)
        user.withdraw_cash!(cash_to_withdraw)
      end
    # end
  end
end
```

It would be nice to have examples using RSpec or any other framework, or maybe a custom spec framework specialized in concurrency tests.

**Comment by dks17** [comment]
Hello.
I think you can find you need around this example:
https://github.com/mongoid/mongoid-locker/blob/1a3e793c9d718e87e6b8002780270d2f68d431c8/spec/support/locker_is_included_shared_examples.rb#L291-L295

https://github.com/mongoid/mongoid-locker/blob/1a3e793c9d718e87e6b8002780270d2f68d431c8/spec/support/populate_database_shared_context.rb#L19-L29

or try
```ruby
document.with_lock do
  the_same_document = Collection.find(document.to_param)

  # it must returns error Mongoid::Locker::Errors::DocumentCouldNotGetLock 
  the_same_doucment.with_lock do
  	# do your stuff
  end
end
```

If you need that the document be already locked consider to use `Mongoid::Locker::Wrapper`
https://github.com/mongoid/mongoid-locker/blob/master/lib/mongoid/locker/wrapper.rb#L21

```ruby
Mongoid::Locker::Wrapper.find_and_lock(doc, opts)

# it must returns error Mongoid::Locker::Errors::DocumentCouldNotGetLock 
doc.with_lock do
  # do your stuff
end
```

Didn't check examples.

**Comment by dblock** [comment]
Closed via https://github.com/mongoid/mongoid-locker/pull/88
