### ISSUE TITLE
mongoid 7.1.0 issue with arguments

### ISSUE THREAD

**Issue by SimonHausdorf** [mongoid/mongoid-locker#85]
something stopped working with mongoid 7.1.0 gem release. It was still fine with 7.1.0.rc0

```
irb(main):001:0> Address.last
Traceback (most recent call last):
        4: from (irb):1
        3: from app/models/address.rb:3:in `<main>'
        2: from app/models/address.rb:8:in `<class:Address>'
        1: from app/models/address.rb:8:in `include'
ArgumentError (wrong number of arguments (given 7, expected 1))
```

address.rb
```
# frozen_string_literal: true

class Address
  # == Inclusions ===========================================================

  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Locker
```

**Comment by dblock** [comment]
Maybe Ruby version-related? Either way try to PR something?

**Comment by SimonHausdorf** [comment]
I will debug more tomorrow. It only happens when `include Mongoid::Locker` is included. And also only when upgrading from mongoid `7.1.0.rc0` to `7.1.0`. We would have to check what changes they made from rc0 to 7.1.0

**Comment by SimonHausdorf** [comment]
I created a new application
```
rails new mongoid-locker-test --skip-active-record --skip-bundle --api
```

added the following gems
```
bundle add mongoid mongoid-locker
```

added a test model
```
class Test

  include Mongoid::Document
  include Mongoid::Locker

  field :address, type: String

end
```

getting the same error
```
irb(main):002:0> Test
Traceback (most recent call last):
        5: from (irb):1
        4: from (irb):2:in `rescue in irb_binding'
        3: from app/models/test.rb:3:in `<main>'
        2: from app/models/test.rb:7:in `<class:Test>'
        1: from app/models/test.rb:7:in `include'
ArgumentError (wrong number of arguments (given 7, expected 1))
```

repository is here: https://github.com/SimonHausdorf/mongoid-locker-test

**Comment by dks17** [comment]
Hello.

**Comment by SimonHausdorf** [comment]
Hey :)

**Comment by dks17** [comment]
@SimonHausdorf began write and pressed ctrl+enter to go to new line. I have finished the comment.

**Comment by dks17** [comment]
@SimonHausdorf this is known issue, see workarounds [here](https://jira.mongodb.org/projects/MONGOID/issues/MONGOID-4849?filter=allopenissues)

**Comment by dks17** [comment]
About strange querying behavior, something similar
[Strange querying behavior in mongoid v7.0.5](https://jira.mongodb.org/projects/MONGOID/issues/MONGOID-4864?filter=allopenissues)

**Comment by phstc** [comment]
👋 I'm also getting this error with mongoid 6.4.5 and mongoid-locker 2.0.1. I couldn't find any workaround to make it work. 

```
SomeModel.first

ArgumentError: wrong number of arguments (given 3, expected 1)
from /Users/pablo.cantero/.asdf/installs/ruby/2.5.3/lib/ruby/2.5.0/forwardable.rb:132:in `instance_delegate'
```

```
    mongoid (6.4.5)
    mongoid-locker (2.0.1)
```

**Comment by phstc** [comment]
I found a workaround using `Module.delegate` instead of `delegate` to ensure it uses the Rails `delegate` helper.
